<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Proximity sensors ring - 7 individual IR proximity detectors arranged 360Â° around robot -->

  <xacro:include filename="$(find nav2_minimal_tb4_description)/urdf/icreate/common_properties.urdf.xacro"/>

  <xacro:macro name="proximity_sensor" params="name parent_link gazebo namespace angle_deg radius z_offset">
    <xacro:property name="angle_rad" value="${angle_deg * deg2rad}"/>
    <xacro:property name="x" value="${radius * cos(angle_rad)}"/>
    <xacro:property name="y" value="${radius * sin(angle_rad)}"/>

    <!-- Individual proximity sensor link -->
    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${z_offset}" rpy="0 0 ${angle_rad}"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="0.008" length="0.005"/>
        </geometry>
        <material name="proximity_sensor_black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.008" length="0.005"/>
        </geometry>
      </collision>
      <xacro:inertial_dummy/>
    </link>

    <!-- Individual IR proximity sensor - narrow beam pointing forward from sensor orientation -->
    <gazebo reference="${name}_link">
      <sensor name="${name}" type="gpu_lidar">
        <always_on>true</always_on>
        <update_rate>10</update_rate>
        <visualize>false</visualize>
        <topic>${namespace}/proximity/${name}</topic>
        <gz_frame_id>${name}_link</gz_frame_id>
        <lidar>
          <scan>
            <horizontal>
              <samples>3</samples>
              <resolution>1.0</resolution>
              <min_angle>-0.087</min_angle>
              <max_angle>0.087</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.01</min>
            <max>0.10</max>
            <resolution>0.005</resolution>
          </range>
        </lidar>
      </sensor>
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>

  <!-- Proximity ring: 7 sensors in forward-facing fan pattern at specified angles -->
  <xacro:macro name="proximity_ring" params="parent_link gazebo namespace radius:=0.162 z_offset:=0.10">
    <xacro:proximity_sensor name="proximity_1" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="-65.3" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_2" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="-38.0" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_3" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="-20.0" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_4" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="-3.0" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_5" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="14.25" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_6" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="34.0" radius="${radius}" z_offset="${z_offset}"/>
    <xacro:proximity_sensor name="proximity_7" parent_link="${parent_link}" gazebo="${gazebo}" namespace="${namespace}" angle_deg="65.3" radius="${radius}" z_offset="${z_offset}"/>
  </xacro:macro>
</robot>
